// apps/workbench-lab/src/app.tsx
import { useCallback, useEffect, useMemo, useRef, useState, type FormEvent } from 'react';

import {
  asPanelId,
  asWidgetInstanceId,
  type WorkbenchState
} from '@pomegranate-ui/contracts';
import { createWidgetRegistry, createWorkbenchStore } from '@pomegranate-ui/core';
import {
  createInitialWorkbenchState,
  createPanel,
  createWidget,
  loadLayout,
  saveLayout,
  type LayoutResult
} from '@pomegranate-ui/layout';
import {
  PanelTabs,
  WorkbenchProvider,
  WorkbenchView,
  createWidgetRendererRegistry
} from '@pomegranate-ui/react';
import { FIRST_SLICE_CONTRACT_IDS } from '@pomegranate-ui/testkit';

import { createLocalLayoutStorage, LAB_LAYOUT_KEY } from './storage.js';
import {
  registerLabWidgets,
  STORY_SUMMARY_TYPE,
  SYSTEM_STATUS_TYPE,
  type LabHostContext
} from './widgets.js';

const scenePanelId = asPanelId('scene');
const libraryPanelId = asPanelId('library');
const summaryWidgetId = asWidgetInstanceId('story-summary');
const statusWidgetId = asWidgetInstanceId('system-status');

function requireState(result: LayoutResult): WorkbenchState {
  if (!result.ok) throw new Error(result.error.message);
  return result.state;
}

function createLabState(): WorkbenchState {
  let state = createInitialWorkbenchState();
  state = requireState(createPanel(state, {
    id: scenePanelId,
    name: 'Scene',
    templateId: 'standard',
    order: 0,
    configuration: { columns: 3 }
  }));
  state = requireState(createPanel(state, {
    id: libraryPanelId,
    name: 'Library',
    templateId: 'library',
    order: 1,
    configuration: { columns: 1 }
  }));
  state = requireState(createWidget(state, {
    id: summaryWidgetId,
    type: STORY_SUMMARY_TYPE,
    manifestVersion: '1.0.0',
    configuration: { density: 'compact' }
  }, {
    kind: 'docked',
    panelId: scenePanelId,
    edge: 'left',
    shelfId: 'primary',
    order: 0
  }));
  state = requireState(createWidget(state, {
    id: statusWidgetId,
    type: SYSTEM_STATUS_TYPE,
    manifestVersion: '1.0.0',
    configuration: { showRevision: true }
  }, {
    kind: 'docked',
    panelId: scenePanelId,
    edge: 'main',
    shelfId: 'primary',
    order: 0
  }));
  return { ...state, revision: 0 };
}

function createRuntime() {
  const registry = createWidgetRegistry();
  const rendererRegistry = createWidgetRendererRegistry<LabHostContext>();
  registerLabWidgets(registry, rendererRegistry);
  return {
    store: createWorkbenchStore({ initialState: createLabState(), registry }),
    rendererRegistry
  };
}

export function App() {
  const runtime = useMemo(createRuntime, []);
  const storage = useMemo(createLocalLayoutStorage, []);
  const hostContext = useMemo<LabHostContext>(() => ({
    storyId: 'story-lab-1',
    systemStatus: 'All systems nominal'
  }), []);
  const [state, setState] = useState(runtime.store.getState());
  const [panelName, setPanelName] = useState('My Panel');
  const [panelTemplate, setPanelTemplate] = useState('standard');
  const [panelColumns, setPanelColumns] = useState(2);
  const [eventLog, setEventLog] = useState<readonly string[]>([]);
  const logSequence = useRef(0);

  const log = useCallback((message: string) => {
    logSequence.current += 1;
    setEventLog((current) => [`${logSequence.current}. ${message}`, ...current].slice(0, 8));
  }, []);

  useEffect(() => runtime.store.subscribe((nextState) => {
    setState(nextState);
    log(`Workbench advanced to revision ${nextState.revision}.`);
  }), [log, runtime.store]);

  useEffect(() => {
    let current = true;
    void loadLayout(storage, LAB_LAYOUT_KEY, runtime.store.getState()).then((loaded) => {
      if (current && loaded.ok) {
        runtime.store.dispatch({ type: 'layout.hydrate', state: loaded.state });
        log('Restored the saved layout on startup.');
      }
    });
    return () => { current = false; };
  }, [log, runtime.store, storage]);

  const activePanel = state.panels.find((panel) => panel.id === state.activePanelId);
  const activeColumns = activePanel?.configuration?.columns;

  const createUserPanel = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const panelId = asPanelId(`user-panel-${state.panels.length - 1}`);
    const created = runtime.store.dispatch({
      type: 'panel.create',
      panel: {
        id: panelId,
        name: panelName,
        templateId: panelTemplate,
        order: state.panels.length,
        configuration: { columns: panelColumns }
      }
    });
    if (created.ok) {
      runtime.store.dispatch({ type: 'panel.activate', panelId });
      log(`Created Panel '${panelName}'.`);
    } else {
      log(`Create rejected: ${created.error.code}.`);
    }
  };

  const save = async () => {
    const saved = await saveLayout(storage, LAB_LAYOUT_KEY, runtime.store.getState());
    log(saved.ok ? 'Saved pomegranate.ui.layout.v1.' : `Save rejected: ${saved.error.code}.`);
  };

  const reloadSaved = async () => {
    const loaded = await loadLayout(storage, LAB_LAYOUT_KEY, runtime.store.getState());
    if (loaded.ok) runtime.store.dispatch({ type: 'layout.hydrate', state: loaded.state });
    log(loaded.ok ? 'Reloaded the saved layout.' : `Reload rejected: ${loaded.error.code}.`);
  };

  const clearSaved = async () => {
    await storage.remove?.(LAB_LAYOUT_KEY);
    log('Cleared the saved layout.');
  };

  const invalidMove = () => {
    const result = runtime.store.dispatch({
      type: 'widget.place',
      instanceId: asWidgetInstanceId('missing-widget'),
      placement: {
        kind: 'docked',
        panelId: state.activePanelId ?? scenePanelId,
        edge: 'right',
        shelfId: 'primary',
        order: 0
      }
    });
    log(result.ok ? 'Unexpectedly accepted invalid move.' : `Invalid move rejected: ${result.error.code}.`);
  };

  return (
    <main>
      <header className="lab-header">
        <div>
          <p className="eyebrow">PomegranateUI private incubator</p>
          <h1>Workbench Lab</h1>
          <p>Inspectable package-consumer proof, not a prescribed application shell.</p>
        </div>
        <dl className="host-context">
          <div><dt>Host story</dt><dd data-testid="story-id">{hostContext.storyId}</dd></div>
          <div><dt>Revision</dt><dd data-testid="current-revision">{state.revision}</dd></div>
        </dl>
      </header>

      <WorkbenchProvider
        store={runtime.store}
        rendererRegistry={runtime.rendererRegistry}
        hostContext={hostContext}
      >
        <section className="control-surface" aria-label="Workbench controls">
          <PanelTabs className="panel-tabs" />
          <p data-testid="active-panel-meta">
            {activePanel
              ? `${activePanel.templateId} · ${typeof activeColumns === 'number' ? activeColumns : 1} columns · order ${activePanel.order}`
              : 'No active Panel'}
          </p>
          <div className="persistence-actions">
            <button type="button" onClick={() => void save()}>Save layout</button>
            <button type="button" onClick={() => void reloadSaved()}>Reload saved layout</button>
            <button type="button" onClick={() => void clearSaved()}>Clear saved layout</button>
            <button type="button" onClick={invalidMove}>Invalid move</button>
          </div>
        </section>

        <WorkbenchView className="workbench" widgetClassName="widget-frame" />
      </WorkbenchProvider>

      <aside className="lab-sidebar">
        <form onSubmit={createUserPanel}>
          <h2>Create a Panel</h2>
          <label>Panel name<input value={panelName} onChange={(event) => setPanelName(event.target.value)} /></label>
          <label>Panel template<input value={panelTemplate} onChange={(event) => setPanelTemplate(event.target.value)} /></label>
          <label>Panel columns<input type="number" min="1" max="4" value={panelColumns} onChange={(event) => setPanelColumns(Number(event.target.value))} /></label>
          <button type="submit">Create Panel</button>
        </form>

        <section>
          <h2>Event log</h2>
          <ol aria-label="Event log">
            {eventLog.length > 0
              ? eventLog.map((entry) => <li key={entry}>{entry}</li>)
              : <li>No transitions yet.</li>}
          </ol>
        </section>

        <details>
          <summary>Native contract evidence</summary>
          <ul>{FIRST_SLICE_CONTRACT_IDS.map((id) => <li key={id}>{id}</li>)}</ul>
        </details>
      </aside>
    </main>
  );
}

// apps/workbench-lab/src/App.svelte
<script lang="ts">
  import { onDestroy, onMount } from 'svelte';
  import { asPanelId, asWidgetInstanceId, type WidgetManifest, type WorkbenchState } from '@pomegranate-ui/contracts';
  import { loadLayout, saveLayout } from '@pomegranate-ui/layout';
  import { setWorkbenchContext, toSvelteCatalogStore } from '@pomegranate-ui/svelte';
  import { FIRST_SLICE_CONTRACT_IDS } from '@pomegranate-ui/testkit';

  import { createLabHostContext, type LabThemeInspector } from './mockup/host-context.js';
  import { createLabRuntime } from './mockup/widgets.js';
  import PanelTabs from './recipes/PanelTabs.svelte';
  import WidgetCatalog from './recipes/WidgetCatalog.svelte';
  import WidgetFrame from './recipes/WidgetFrame.svelte';
  import WorkbenchSurface from './recipes/WorkbenchSurface.svelte';
  import { createLocalLayoutStorage, LAB_LAYOUT_KEY } from './storage.js';
  import { createLabThemeController } from './themes/controller.js';
  import { LAB_THEME_PRESETS } from './themes/presets.js';
  import { createLocalThemePreference } from './themes/theme-storage.js';

  const runtime = createLabRuntime();
  const storage = createLocalLayoutStorage();
  const { store, catalog, rendererRegistry } = runtime;
  const catalogState = toSvelteCatalogStore(catalog);
  const themeController = createLabThemeController({ preference: createLocalThemePreference(window.localStorage) });
  const initialThemeSnapshot = themeController.getSnapshot();
  let themeSnapshot = $state(initialThemeSnapshot);

  function themeInspector(): LabThemeInspector {
    return {
      colors: themeSnapshot.resolved.colors,
      typography: [
        themeSnapshot.resolved.typography.ui.family,
        themeSnapshot.resolved.typography.prose.family,
        themeSnapshot.resolved.typography.technical.family
      ],
      geometry: `${themeSnapshot.resolved.geometry.cornerFamily} · ${themeSnapshot.resolved.geometry.cornerMd}px`,
      density: themeSnapshot.resolved.spacing.density,
      iconPackId: themeSnapshot.resolved.iconPackId
    };
  }

  function activateTheme(id: string) {
    const result = themeController.activate(id);
    if (result.ok) {
      themeSnapshot = result.snapshot;
      hostContext.theme.activeId = result.snapshot.activeId;
      hostContext.theme.inspector = themeInspector();
      status = `${result.snapshot.resolved.label} applied without changing Workbench state.`;
    } else {
      status = result.diagnostics[0]?.message ?? 'Theme activation failed.';
    }
  }

  let hostContext = $state(createLabHostContext({
    activeId: initialThemeSnapshot.activeId,
    presets: LAB_THEME_PRESETS.map(({ id, definition }) => ({
      id,
      label: definition.label,
      description: definition.description ?? definition.label
    })),
    inspector: themeInspector(),
    activate: activateTheme
  }));
  setWorkbenchContext({ store, catalog, rendererRegistry, hostContext });

  let workbench: WorkbenchState = $state(store.getState());
  let focusMode = $state(false);
  let leftCollapsed = $state(false);
  let panelDialog: HTMLDialogElement;
  let panelName = $state('New Panel');
  let status = $state('Local mockup ready.');
  let eventLog: string[] = $state([]);
  let sequence = 0;

  const unsubscribe = store.subscribe((next) => {
    workbench = next;
    sequence += 1;
    eventLog = [`${sequence}. Workbench advanced to revision ${next.revision}.`, ...eventLog].slice(0, 6);
  });
  onDestroy(unsubscribe);

  onMount(() => {
    let current = true;
    void loadLayout(storage, LAB_LAYOUT_KEY, store.getState()).then((loaded) => {
      if (current && loaded.ok) {
        store.dispatch({ type: 'layout.hydrate', state: loaded.state });
        status = 'Restored the saved local layout.';
      }
    });
    return () => { current = false; };
  });

  const activePanel = $derived(workbench.panels.find((panel) => panel.id === workbench.activePanelId));

  function floatingStyle(frame: { placement: { kind: string; x?: number; y?: number; width?: number; height?: number; z?: number } }) {
    if (frame.placement.kind !== 'floating') return '';
    return `left:${frame.placement.x}px;top:${frame.placement.y}px;width:${frame.placement.width}px;min-height:${frame.placement.height}px;z-index:${frame.placement.z}`;
  }

  function addFromCatalog(manifest: WidgetManifest) {
    const panelId = workbench.activePanelId;
    if (!panelId) return;
    const id = asWidgetInstanceId(`catalog-${manifest.type.replace(/[^a-z0-9]+/gi, '-')}-${workbench.revision + 1}`);
    const edge = manifest.defaultPlacement.kind === 'docked' ? manifest.defaultPlacement.edge : 'main';
    const result = store.dispatch({
      type: 'widget.create',
      instance: { id, type: manifest.type, manifestVersion: manifest.version, configuration: {} },
      placement: { kind: 'docked', panelId, edge, shelfId: 'primary', order: Number.MAX_SAFE_INTEGER }
    });
    status = result.ok ? `${manifest.title} added to ${activePanel?.name ?? 'Panel'}.` : result.error.message;
  }

  function createPanel(event: SubmitEvent) {
    event.preventDefault();
    const id = asPanelId(`user-panel-${workbench.panels.length - 2}`);
    const result = store.dispatch({
      type: 'panel.create',
      panel: { id, name: panelName.trim() || 'Untitled Panel', templateId: 'columns.v1', order: workbench.panels.length, configuration: { columns: 2 } }
    });
    if (result.ok) {
      store.dispatch({ type: 'panel.activate', panelId: id });
      panelDialog.close();
      status = `${panelName} created.`;
    } else status = result.error.message;
  }

  async function save() {
    const result = await saveLayout(storage, LAB_LAYOUT_KEY, store.getState());
    status = result.ok ? 'Saved pomegranate.ui.layout.v1 locally.' : result.error.message;
  }

  async function reload() {
    const result = await loadLayout(storage, LAB_LAYOUT_KEY, store.getState());
    if (result.ok) store.dispatch({ type: 'layout.hydrate', state: result.state });
    status = result.ok ? 'Reloaded the saved local layout.' : result.error.message;
  }

  async function clear() {
    await storage.remove?.(LAB_LAYOUT_KEY);
    status = 'Cleared the saved local layout.';
  }

  function openPanelDialog() {
    panelDialog.showModal();
  }
</script>

<svelte:head><title>PomegranateUI Workbench Lab</title></svelte:head>

<main
  class:focus-mode={focusMode}
  class:left-collapsed={leftCollapsed}
  data-pom-theme={themeSnapshot.activeId}
  data-workbench-revision={workbench.revision}
  style={themeSnapshot.cssText}
>
  <div class="atmosphere" aria-hidden="true"><i></i><i></i><i></i></div>
  <header class="top-shelf">
    <a class="wordmark" href="#workbench"><span aria-hidden="true">P</span><strong>PomegranateUI</strong><small>Workbench Lab</small></a>
    <PanelTabs {store} class="panel-tabs" />
    <div class="story-lockup">
      <span>Active story</span>
      <strong>{hostContext.storyTitle}</strong>
      <small aria-label="Active story identity">{hostContext.storyId} · {hostContext.frameLabel}</small>
    </div>
    <div class="shelf-actions">
      <button type="button" aria-label="Open Widget Catalog" aria-expanded={$catalogState.open} onclick={() => catalog.open('drawer')}>Widgets</button>
      <button type="button" aria-pressed={focusMode} onclick={() => { focusMode = !focusMode; }}>Focus reading</button>
      <span class="runtime-status"><i></i>{hostContext.systemStatus}</span>
    </div>
  </header>

  <section class="context-rail" aria-label="Workbench context">
    <p><span>{activePanel?.templateId ?? 'No Panel'}</span><strong>{activePanel?.name ?? 'No active Panel'}</strong></p>
    <div class="dock-controls">
      <button type="button" aria-pressed={leftCollapsed} onclick={() => { leftCollapsed = !leftCollapsed; }}>Collapse left dock</button>
      <button type="button" onclick={openPanelDialog}>Create Panel</button>
    </div>
    <div class="persistence-actions">
      <button type="button" onclick={() => void save()}>Save layout</button>
      <button type="button" onclick={() => void reload()}>Reload saved layout</button>
      <button type="button" onclick={() => void clear()}>Clear saved layout</button>
    </div>
  </section>

  <section id="workbench" class="workbench-shell" aria-label="Active Workbench">
    <WorkbenchSurface {store} class="workbench-surface">
      {#snippet renderWidget(frame)}
        <div class:widget-float={frame.placement.kind === 'floating'} style={floatingStyle(frame)}>
          <WidgetFrame
            {frame}
            {store}
            {rendererRegistry}
            {hostContext}
            class="widget-frame"
          />
        </div>
      {/snippet}
    </WorkbenchSurface>
  </section>

  <footer class="lab-footer">
    <p role="status" aria-live="polite">{status}</p>
    <details><summary>Event log</summary><ol>{#each eventLog as entry}<li>{entry}</li>{/each}</ol></details>
    <details><summary>Native contract evidence</summary><ul>{#each FIRST_SLICE_CONTRACT_IDS as id}<li>{id}</li>{/each}</ul></details>
  </footer>

  <WidgetCatalog {catalog} oncreate={addFromCatalog} class="widget-catalog" />

  <dialog bind:this={panelDialog} aria-labelledby="panel-dialog-title">
    <form onsubmit={createPanel}>
      <h2 id="panel-dialog-title">Create a Panel</h2>
      <label>Panel name<input bind:value={panelName} /></label>
      <p>Starts as an adopter-owned two-column layout.</p>
      <div><button type="button" onclick={() => panelDialog.close()}>Cancel</button><button type="submit">Create Panel</button></div>
    </form>
  </dialog>
</main>
